# arb-dir: lib/src/localization
# template-arb-file: app_en.arb
# output-localization-file: app_localizations.dart
# nullable-getter: false
# untranslated-messages-file: untranslated_messages.txt

arb-dir: lib/src/localization
template-arb-file: app_en.arb
synthetic-package: false
output-dir: lib/src/localization/gen_l10n
output-localization-file: app_localizations.dart
nullable-getter: false
untranslated-messages-file: untranslated_messages.txt
use-escaping: false