name: irrigazione_iot
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.6+8

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  cloud_functions: ^4.7.3
  collection: ^1.18.0
  dio: ^5.7.0
  envied: ^0.5.4+1
  equatable: ^2.0.5
  firebase_core: ^2.30.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  geolocator: ^13.0.1
  get_it: ^8.0.0
  go_router: ^13.1.0
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.9.0
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.9.0
  mqtt_client: ^10.2.1
  path_provider: ^2.1.4
  riverpod_annotation: ^2.3.4
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.2
  skeletonizer: ^1.0.1
  supabase_flutter: ^2.5.1
  timeago: ^3.6.1
  timeago_flutter: ^3.6.0
  typed_data: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.13
  custom_lint: ^0.5.11
  riverpod_lint: ^2.1.1
  riverpod_generator: ^2.3.3
  json_serializable: ^6.8.0
  envied_generator: ^0.5.4+1
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.5.2
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/weenat/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_gen:
  output: lib/gen/

  integrations:
    flutter_svg: true

  assets:
    enabled: true
  fonts:
    enabled: false
  colors:
    enabled: false