name: irrigazione_iot
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  envied: ^0.5.4+1
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^13.1.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.4
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  skeletonizer: ^1.0.1
  supabase_flutter: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  custom_lint: ^0.5.11
  riverpod_lint: ^2.3.7
  riverpod_generator: ^2.3.9
  mocktail: ^1.0.3
  json_serializable: ^6.7.1
  envied_generator: ^0.5.4+1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
