create table
  public.pump_flows (
    id bigint generated by default as identity,
    flow double precision not null,
    pump_id bigint not null,
    created_at timestamp with time zone not null default now(),
    constraint pump_flows_pkey primary key (id),
    constraint public_pump_flows_pump_id_fkey foreign key (pump_id) references pumps (id) on update restrict on delete cascade
  ) tablespace pg_default;