create table
  public.pumps (
    id bigint generated by default as identity,
    name character varying not null,
    capacity_in_volume double precision not null,
    consume_rate_in_kw double precision not null,
    company_id bigint not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null,
    constraint pumps_pkey primary key (id),
    constraint public_pumps_company_id_fkey foreign key (company_id) references companies (id) on update restrict on delete cascade
  ) tablespace pg_default;