create table
  public.sector_pumps (
    id bigint generated by default as identity,
    sector_id bigint not null,
    pump_id bigint not null,
    created_at timestamp with time zone not null default now(),
    constraint sector_pumps_pkey primary key (id),
    constraint public_sector_pumps_pump_id_fkey foreign key (pump_id) references pumps (id) on update restrict on delete cascade,
    constraint public_sector_pumps_sector_id_fkey foreign key (sector_id) references sectors (id) on update restrict on delete cascade
  ) tablespace pg_default;