create table if not exists
  public.varieties (
    id bigint generated by default as identity,
    name character varying not null,
    created_at timestamp with time zone not null default now(),
    constraint varieties_pkey primary key (id),
    constraint varieties_name_key unique (name)
  ) tablespace pg_default;