create table if not exists
  public.companies_user (
    id bigint generated by default as identity,
    email character varying not null,
    full_name character varying not null,
    role character varying not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    company_id bigint not null,
    constraint companies_user_pkey primary key (id),
    constraint companies_user_id_key unique (id),
    constraint public_companies_user_company_id_fkey foreign key (company_id) references companies (id) on update restrict on delete cascade
  ) tablespace pg_default;