create table if not exists
  public.species (
    id bigint generated by default as identity,
    name character varying not null,
    created_at timestamp with time zone not null default now(),
    constraint species_pkey primary key (id)
  ) tablespace pg_default;