create table
  public.boards (
    id bigint generated by default as identity,
    name character varying not null,
    model character varying not null,
    serial_number character varying not null,
    collector_id bigint not null,
    company_id bigint not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null,
    constraint boards_pkey primary key (id),
    constraint boards_name_key unique (name),
    constraint public_boards_collector_id_fkey foreign key (collector_id) references collectors (id) on update restrict on delete cascade,
    constraint public_boards_company_id_fkey foreign key (company_id) references companies (id) on update restrict on delete cascade
  ) tablespace pg_default;