create table
  public.collector_pressure (
    event_id bigint generated by default as identity,
    filter_in_pressure double precision not null,
    filter_out_pressure double precision not null,
    pressure_difference double precision not null GENERATED ALWAYS AS (filter_in_pressure - filter_out_pressure) STORED,
    pressure_timestamp timestamp with time zone not null,
    collector_id bigint not null,
    constraint collector_pressure_pkey primary key (event_id),
    constraint public_collector_pressure_collector_id_fkey foreign key (collector_id) references collectors (id) on update restrict on delete cascade
  ) tablespace pg_default;