create table if not exists
  public.sector_statuses (
    status_id bigint generated by default as identity,
    status character varying not null,
    sector_id bigint not null,
    status_timestamp timestamp with time zone not null,
    constraint sector_statuses_pkey primary key (status_id),
    constraint public_sector_statuses_sector_id_fkey foreign key (sector_id) references sectors (id) on update restrict on delete cascade
  ) tablespace pg_default;