create table
  public.companies (
    id bigint generated by default as identity,
    name text not null,
    email text not null,
    phone_number text not null,
    registered_office_address text not null,
    cf text null,
    piva text null,
    image_url text null,
    constraint companies_pkey primary key (id),
    constraint companies_id_key unique (id)
  ) tablespace pg_default;