create table if not exists
  public.pump_pressures (
    event_id bigint generated by default as identity,
    pressure double precision not null,
    pressure_timestamp timestamp with time zone not null,
    pump_id bigint not null,
    constraint pump_pressures_pkey primary key (event_id),
    constraint public_pump_pressures_pump_id_fkey foreign key (pump_id) references pumps (id) on update restrict on delete cascade
  ) tablespace pg_default;