create table
  public.terminal_pressure (
    id bigint generated by default as identity,
    pressure double precision not null,
    created_at timestamp with time zone not null default now(),
    collector_id bigint not null,
    constraint terminal_pressure_pkey primary key (id),
    constraint public_terminal_pressure_collector_id_fkey foreign key (collector_id) references collectors (id) on update restrict on delete cascade
  ) tablespace pg_default;