create table if not exists
  public.sector_pressures (
    event_id bigint generated by default as identity,
    pressure double precision not null,
    pressure_timestamp timestamp with time zone not null,
    sector_id bigint not null,
    constraint sector_pressures_pkey primary key (event_id),
    constraint public_sector_pressures_sector_id_fkey foreign key (sector_id) references sectors (id) on update restrict on delete cascade
  ) tablespace pg_default;