drop policy "Superusers and company members can select" on "public"."sensor_battery_data";

revoke delete on table "public"."sensor_battery_data"
from
    "anon";

revoke insert on table "public"."sensor_battery_data"
from
    "anon";

revoke references on table "public"."sensor_battery_data"
from
    "anon";

revoke
select
    on table "public"."sensor_battery_data"
from
    "anon";

revoke trigger on table "public"."sensor_battery_data"
from
    "anon";

revoke truncate on table "public"."sensor_battery_data"
from
    "anon";

revoke
update on table "public"."sensor_battery_data"
from
    "anon";

revoke delete on table "public"."sensor_battery_data"
from
    "authenticated";

revoke insert on table "public"."sensor_battery_data"
from
    "authenticated";

revoke references on table "public"."sensor_battery_data"
from
    "authenticated";

revoke
select
    on table "public"."sensor_battery_data"
from
    "authenticated";

revoke trigger on table "public"."sensor_battery_data"
from
    "authenticated";

revoke truncate on table "public"."sensor_battery_data"
from
    "authenticated";

revoke
update on table "public"."sensor_battery_data"
from
    "authenticated";

revoke delete on table "public"."sensor_battery_data"
from
    "service_role";

revoke insert on table "public"."sensor_battery_data"
from
    "service_role";

revoke references on table "public"."sensor_battery_data"
from
    "service_role";

revoke
select
    on table "public"."sensor_battery_data"
from
    "service_role";

revoke trigger on table "public"."sensor_battery_data"
from
    "service_role";

revoke truncate on table "public"."sensor_battery_data"
from
    "service_role";

revoke
update on table "public"."sensor_battery_data"
from
    "service_role";

alter table "public"."sensor_battery_data"
drop constraint "public_sensor_battery_data_sensor_id_fkey";

alter table "public"."sensor_battery_data"
drop constraint "sensor_battery_data_pkey";

drop index if exists "public"."sensor_battery_data_pkey";

drop table "public"."sensor_battery_data";

create table
    "public"."weather_station_battery_data" (
        "id" bigint generated by default as identity not null,
        "battery_level" numeric not null,
        "weather_station_id" bigint not null,
        "created_at" timestamp
        with
            time zone not null default now ()
    );

alter table "public"."weather_station_battery_data" enable row level security;

CREATE UNIQUE INDEX sensor_battery_data_pkey ON public.weather_station_battery_data USING btree (id);

alter table "public"."weather_station_battery_data" add constraint "sensor_battery_data_pkey" PRIMARY KEY using index "sensor_battery_data_pkey";

alter table "public"."weather_station_battery_data" add constraint "public_weather_station_battery_data_weather_station_id_fkey" FOREIGN KEY (weather_station_id) REFERENCES weather_stations (id) ON UPDATE RESTRICT ON DELETE CASCADE not valid;

alter table "public"."weather_station_battery_data" validate constraint "public_weather_station_battery_data_weather_station_id_fkey";

grant delete on table "public"."weather_station_battery_data" to "anon";

grant insert on table "public"."weather_station_battery_data" to "anon";

grant references on table "public"."weather_station_battery_data" to "anon";

grant
select
    on table "public"."weather_station_battery_data" to "anon";

grant trigger on table "public"."weather_station_battery_data" to "anon";

grant truncate on table "public"."weather_station_battery_data" to "anon";

grant
update on table "public"."weather_station_battery_data" to "anon";

grant delete on table "public"."weather_station_battery_data" to "authenticated";

grant insert on table "public"."weather_station_battery_data" to "authenticated";

grant references on table "public"."weather_station_battery_data" to "authenticated";

grant
select
    on table "public"."weather_station_battery_data" to "authenticated";

grant trigger on table "public"."weather_station_battery_data" to "authenticated";

grant truncate on table "public"."weather_station_battery_data" to "authenticated";

grant
update on table "public"."weather_station_battery_data" to "authenticated";

grant delete on table "public"."weather_station_battery_data" to "service_role";

grant insert on table "public"."weather_station_battery_data" to "service_role";

grant references on table "public"."weather_station_battery_data" to "service_role";

grant
select
    on table "public"."weather_station_battery_data" to "service_role";

grant trigger on table "public"."weather_station_battery_data" to "service_role";

grant truncate on table "public"."weather_station_battery_data" to "service_role";

grant
update on table "public"."weather_station_battery_data" to "service_role";

create policy "Superusers and company members can select" on "public"."weather_station_battery_data" as permissive for
select
    to authenticated using (
        (
            (
                EXISTS (
                    SELECT
                        1
                    FROM
                        companies
                    WHERE
                        (
                            companies.id = get_sensor_company_id (weather_station_battery_data.weather_station_id)
                        )
                )
            )
            OR check_if_user_is_superuser (get_user_email_v2 ())
        )
    );