name: Run Tests
on: [push, workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: echo "${{ github.workspace }}/app/test"
      - working-directory: ${{ github.workspace }}/app/test
        run: flutter test
