name: Run flutter tests
on: [push, workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - working-directory: app
      - name: Run tests
        run: |
        flutter pub get
        dart run build_runner build -d
        flutter test
        
