name: Run Tests
on: [push, workflow_dispatch]
run-name: ${{ github.actor }} is running automatic GitHub Actions
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v1
      - run: flutter test
